set completeopt=longest,menu    "让Vim的补全菜单行为与一般IDE一致(参考VimTip1228)
autocmd InsertLeave * if pumvisible() == 0|pclose|endif "离开插入模式后自动关闭预览窗口
inoremap <expr> <CR>       pumvisible() ? "\<C-y>" : "\<CR>"    "回车即选中当前项
"上下左右键的行为 会显示其他信息
inoremap <expr> <Down>     pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Up>       pumvisible() ? "\<C-p>" : "\<Up>"
inoremap <expr> <PageDown> pumvisible() ? "\<PageDown>\<C-p>\<C-n>" : "\<PageDown>"
inoremap <expr> <PageUp>   pumvisible() ? "\<PageUp>\<C-p>\<C-n>" : "\<PageUp>"
" 跳转到定义处
nnoremap <leader>jd :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <F6> :YcmForceCompileAndDiagnostics<CR>    "force recomile with syntastic
" nnoremap <leader>lo :lopen<CR>    "open locationlist
" nnoremap <leader>lc :lclose<CR>   "close locationlist
inoremap <leader><leader> <C-x><C-o>

"basic setting
set nu
syntax on
"set tab
set ts=4
set expandtab
set autoindent
set list
set lcs=tab:\|\ ,nbsp:%,trail:-
set foldmethod=syntax
set nofoldenable

" vbundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" 加载插件
Plugin 'VundleVim/Vundle.vim'
Plugin 'preservim/nerdtree'
Bundle 'luochen1990/rainbow'
Plugin 'https://github.com/antoyo/vim-licenses.git'
call vundle#end()
filetype plugin indent on     " required
let g:rainbow_active = 1

"vim json format
let mapleader=","

"NERDTree config
autocmd VimEnter * NERDTree
let g:NERDTreeShowHidden=1

"hightlight some info
if has("autocmd")
   " Highlight TODO, FIXME, NOTE, etc.
   if v:version > 701
      autocmd syntax * call matchadd('Todo','\W\zs\(TODO\|FIXME\|CHANGED\|BUG\|HACK\)')
      autocmd syntax * call matchadd('Debug','\W\zs\(NOTE\|INFO\|IDEA\)')
      hi Debug  ctermbg=LightYellow ctermfg=Black
   endif
endif


"highlight line and column
set cursorline
hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
set cursorcolumn
hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white

"display file path and its status
set laststatus=2
function! CurDir()
   let curdir=substitute(getcwd(),$HOME,"~","g")
   return curdir
endfunction
set statusline=[%n]\ %f%m%r%h\ \|\ \ pwd:\ %{CurDir()}\ \ \|%=\|\ %l,%c\ %p%%\ \|\ ascii=%b,hex=%b%{((&fenc==\"\")?\"\":\"\ \|\ \".&fenc)}\ \|\ %{$USER}\ @\ %{hostname()}\

"vim-license
let g:licenses_authors_name = 'Xin, Liu <@liuxin_signal@163.com>'
let g:licenses_default_commands = ['gpl', 'mit']
